### ISSUE TITLE
LDAPSearchError

### ISSUE THREAD

**Issue by jamesbcook** [the-useless-one/pywerview#26]
Hello,

When trying to run some of the modules I run into the following error:

```
pywerview get-netfileserver -w ACME -u john.smith -p hunter2 -t 192.168.1.2  

impacket.ldap.ldap.LDAPSearchError: Error in searchRequest -> 'referral': 0000202B: RefErr: DSID-0310082F, data 0, 1 access points
```

**Comment by the-useless-one** [comment]
Hi!

In the `-w` parameter, you must put the domain name in its long version, aka the post-Win2k UPN, and not in its Win2k compatible form. I talk about this [here](https://github.com/the-useless-one/pywerview#functionalities) (go to the end of the "Functionalities" block). I'll put it bigger so that people don't miss it anymore.

Cheers,

Y

**Comment by jamesbcook** [comment]
wow, sorry about that. That's embarrassing.

**Comment by the-useless-one** [comment]
No problem ;)
